site_name: I2C Commander
theme:
  name: material
  logo:
    images/i2cc-logo.png
  features:
    - navigation.sections

# Markdown extensions
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - "Introduction": "index.md"
  - "Installation": "install.md"
  - "Low level access": "bare_i2c.md"
  - "Register model level access": "register_i2c.md"
  - "High level programming": "high_level_i2c.md"
